services:
  url-shortener:
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    build:
      dockerfile: ./Dockerfile
      context: ./
    depends_on:
      storage:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "5050:5050"
    environment:
      - SHORTENER_CONFIG=config/docker.yml
    volumes:
      - ./logs/url-shortener:/app/logs
    entrypoint: ["./shortener-app", "-redis"]

  storage:
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:15.4-alpine
    container_name: storage
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  cache:
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    image: redis:latest
    container_name: cache
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"

  migrator:
    build:
      dockerfile: migration/migrator/Dockerfile
      context: ./
    depends_on:
      storage:
        condition: service_healthy
    entrypoint: ["sql-migrate", "up", "-config", "migration/migrator/config/dbconfig.yml", "-env=docker"]

  tests:
    build:
      dockerfile: tests/Dockerfile
      context: ./
    depends_on:
      url-shortener:
        condition: service_healthy
    environment:
      - GRPC_HOST=url-shortener:5050
      - HTTP_HOST=url-shortener:8080
    profiles:
      - test