// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// URL is an autogenerated mock type for the URL type
type URL struct {
	mock.Mock
}

// CreateOrGetShortenedURL provides a mock function with given fields: ctx, original, shortened
func (_m *URL) CreateOrGetShortenedURL(ctx context.Context, original string, shortened string) (string, error) {
	ret := _m.Called(ctx, original, shortened)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGetShortenedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, original, shortened)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, original, shortened)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, original, shortened)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOriginalURLByShortened provides a mock function with given fields: ctx, shortened
func (_m *URL) GetOriginalURLByShortened(ctx context.Context, shortened string) (string, error) {
	ret := _m.Called(ctx, shortened)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURLByShortened")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortened)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortened)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortened)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShortenedURLByOriginal provides a mock function with given fields: ctx, original
func (_m *URL) GetShortenedURLByOriginal(ctx context.Context, original string) (string, error) {
	ret := _m.Called(ctx, original)

	if len(ret) == 0 {
		panic("no return value specified for GetShortenedURLByOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, original)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, original)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, original)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURL creates a new instance of URL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURL(t interface {
	mock.TestingT
	Cleanup(func())
}) *URL {
	mock := &URL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
