basePath: /api/v1/
definitions:
  responses.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  types.GetOriginalURLResponse:
    properties:
      originalURL:
        type: string
    type: object
  types.PostShortURLRequest:
    properties:
      original_url:
        type: string
    type: object
  types.PostShortURLResponse:
    properties:
      shortened_url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for URL Shortener service
  termsOfService: http://swagger.io/terms/
  title: URL Shortener API
  version: "1.0"
paths:
  /urls:
    post:
      consumes:
      - application/json
      description: |-
        Accepts a JSON payload containing the original URL and returns a generated shortened URL.

        The provided `original_url` must be a valid, publicly accessible URL.
        - If the URL does not include an HTTP scheme (`http://` or `https://`), the service will automatically prepend `https://`.
        - If the provided URL results in more than **1 redirect**, the response will contain the URL state at the **1st redirect**.

        If a shortened URL already exists for the given original URL, the existing shortened URL will be returned.
      parameters:
      - description: Original URL (must be publicly accessible; if no HTTP scheme
          is provided, `https://` is added automatically; URLs with more than 10 redirects
          return the last reachable state).
        in: body
        name: original_url
        required: true
        schema:
          $ref: '#/definitions/types.PostShortURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created or retrieved an existing shortened URL
          schema:
            $ref: '#/definitions/types.PostShortURLResponse'
        "400":
          description: 'Invalid request: the provided URL is malformed, inaccessible,
            or empty'
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "408":
          description: 'Request timeout: exceeded server execution time or client
            disconnected'
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal service error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Create a shortened URL
  /urls/{shortened}:
    get:
      description: |-
        Given a shortened URL, returns the corresponding original URL.

        The `shortened` URL must be exactly **10 characters long** and consist only of:
        - Uppercase and lowercase English letters (`A-Z, a-z`)
        - Digits (`0-9`)
        - Underscore (`_`)
      parameters:
      - description: Shortened URL (must be 10 characters long and follow the defined
          character set)
        in: path
        name: shortened
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved the original URL
          schema:
            $ref: '#/definitions/types.GetOriginalURLResponse'
        "400":
          description: 'Invalid format: incorrect length or invalid characters in
            the shortened URL'
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Shortened URL not found in the system
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "408":
          description: 'Request timeout: exceeded server execution time or client
            disconnected'
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal service error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Retrieve the original URL
swagger: "2.0"
